pipeline{
    agent any

    parameters{
        choice(choices: ["TEST", "DEV", "QA", "PREPROD", "PROD"], description: "Which environment to deploy in?", name: "deployEnv")
    }

    stages{
        stage("Demo"){
            
            steps{
                echo "Choice is set to: ${params.deployEnv}"

            }
        }
    }
}